const $=id=>document.getElementById(id);const status=$('status');
function config(){return {server:$('server').value.trim()};}
function save(){chrome.runtime.sendMessage({type:'SAVE_CONFIG',...config()});chrome.storage.local.set(config());}
function render(s){if(s.server){$('server').value=s.server;$('settings-summary').textContent='连接设置（已配置）';}else{$('settings-summary').textContent='连接设置（请先填写服务器地址）';$('connection-settings').open=true;}if(s.room){$('room-box').classList.remove('hidden');$('room-code').textContent=s.room;$('room-connection').textContent=s.connected?'已连接':'连接中 / 正在重连';$('room-members').textContent=`房间人数：${s.memberCount||0}/${s.roomLimit||4}`;const nav=s.pendingNavigation||s.sharedNavigation;if(nav){$('navigation-panel').classList.remove('hidden');$('navigation-title').textContent=s.pendingNavigation?`主机分享：${nav.title||nav.url}`:`当前分享：${nav.title||nav.url}`;$('navigation-url').textContent=nav.url||'';$('navigation-url').href=nav.url||'#';$('follow-actions').classList.toggle('hidden',!s.pendingNavigation);const members=(s.members||[]).filter(id=>id!==s.hostClientId);const labels={pending:'待回应',following:'已跟随', 'not-following':'未跟随'};$('follow-summary').textContent=members.length?members.map((id,i)=>{const response=(s.followResponses||[]).find(r=>r.clientId===id);return `成员 ${i+1}：${labels[response?.status]||'待回应'}`;}).join('　'):'目前没有其他成员。';}else $('navigation-panel').classList.add('hidden');}else $('room-box').classList.add('hidden');if(s.status)status.textContent=s.status;}
chrome.storage.local.get(['server','room','status','connected','memberCount','roomLimit','members','hostClientId','pendingNavigation','sharedNavigation','followResponses'],render);chrome.runtime.onMessage.addListener(m=>{if(m.type==='STATE')render(m.state);});
$('server').addEventListener('change',()=>{save();$('server').type='password';$('toggle-server').textContent='显示';$('connection-settings').open=false;$('settings-summary').textContent='连接设置（已配置）';});
$('toggle-server').onclick=()=>{const input=$('server'),visible=input.type==='password';input.type=visible?'text':'password';$('toggle-server').textContent=visible?'隐藏':'显示';};
$('follow-yes').onclick=()=>chrome.runtime.sendMessage({type:'FOLLOW_DECISION',follow:true});
$('follow-no').onclick=()=>chrome.runtime.sendMessage({type:'FOLLOW_DECISION',follow:false});
async function getTab(){const [t]=await chrome.tabs.query({active:true,currentWindow:true});return t;}
$('create').onclick=async()=>{save();const t=await getTab();chrome.runtime.sendMessage({type:'CREATE_ROOM',server:$('server').value.trim(),tabId:t?.id});};
$('join').onclick=async()=>{save();const t=await getTab();chrome.runtime.sendMessage({type:'JOIN_ROOM',server:$('server').value.trim(),room:$('room-input').value.trim(),tabId:t?.id});};
$('leave').onclick=()=>chrome.runtime.sendMessage({type:'LEAVE'});
$('copy-room').onclick=async()=>{await navigator.clipboard.writeText($('room-code').textContent);status.textContent='房间码已复制。'};
